### ISSUE TITLE
Can't compile / build at all on 9.2 or 9.4

### ISSUE THREAD

**Issue by danwdart** [yav/graphmod#44]
Hello, having an issue building/compiling at all on > 9.0:

ghc94 output:

```
[4 of 5] Compiling CabalSupport     ( src/CabalSupport.hs, dist/build/graphmod/graphmod-tmp/CabalSupport.o )

src/CabalSupport.hs:20:47: error:
    Module
    ‘Distribution.PackageDescription.Parsec’
    does not export
    ‘readGenericPackageDescription’
   |
20 | import Distribution.PackageDescription.Parsec(readGenericPackageDescription)
```

ghc92 output:
```
src/CabalSupport.hs:68:37: error:
    • Couldn't match type: Distribution.Utils.Path.SymbolicPath
                             Distribution.Utils.Path.PackageDir
                             Distribution.Utils.Path.SourceDir
                     with: [Char]
      Expected: [FilePath]
        Actual: [Distribution.Utils.Path.SymbolicPath
                   Distribution.Utils.Path.PackageDir
                   Distribution.Utils.Path.SourceDir]
    • In the ‘unitPaths’ field of a record
      In the expression:
        Unit
          {unitName = UnitLibrary,
           unitPaths = hsSourceDirs (libBuildInfo lib),
           unitModules = map toMod (exposedModules lib), unitFiles = []}
      In an equation for ‘libUnit’:
          libUnit lib
            = Unit
                {unitName = UnitLibrary,
                 unitPaths = hsSourceDirs (libBuildInfo lib),
                 unitModules = map toMod (exposedModules lib), unitFiles = []}
   |
68 |                    , unitPaths    = hsSourceDirs (libBuildInfo lib)
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/CabalSupport.hs:76:36: error:
    • Couldn't match type: Distribution.Utils.Path.SymbolicPath
                             Distribution.Utils.Path.PackageDir
                             Distribution.Utils.Path.SourceDir
                     with: [Char]
      Expected: [FilePath]
        Actual: [Distribution.Utils.Path.SymbolicPath
                   Distribution.Utils.Path.PackageDir
                   Distribution.Utils.Path.SourceDir]
    • In the ‘unitPaths’ field of a record
      In the expression:
        Unit
          {unitName = UnitExecutable (pretty $ exeName exe),
           unitPaths = hsSourceDirs (buildInfo exe), unitModules = [],
           unitFiles = case hsSourceDirs (buildInfo exe) of
                         [] -> [modulePath exe]
                         ds -> [d </> modulePath exe | d <- ds]}
      In an equation for ‘exeUnit’:
          exeUnit exe
            = Unit
                {unitName = UnitExecutable (pretty $ exeName exe),
                 unitPaths = hsSourceDirs (buildInfo exe), unitModules = [],
                 unitFiles = case hsSourceDirs (buildInfo exe) of
                               [] -> [...]
                               ds -> [d </> modulePath exe | d <- ds]}
   |
76 |                    , unitPaths   = hsSourceDirs (buildInfo exe)
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/CabalSupport.hs:80:46: error:
    • Couldn't match expected type: [Char]
                  with actual type: Distribution.Utils.Path.SymbolicPath
                                      Distribution.Utils.Path.PackageDir
                                      Distribution.Utils.Path.SourceDir
    • In the first argument of ‘(</>)’, namely ‘d’
      In the expression: d </> modulePath exe
      In the expression: [d </> modulePath exe | d <- ds]
   |
80 |                                      ds -> [ d </> modulePath exe | d <- ds ]
   |                                              ^
```

Is there any chance of an upgrade? Thanks!

**Comment by yav** [comment]
Thanks for reporting this.  Can you try the current `master` branch?  I just pushed an update that makes it work with GHC 9.4.3 and I was also able to build it with `ghc-9.2.5`

**Comment by danwdart** [comment]
Ah, okay. I was using the latest available on unstable nixpkgs which tracks hackage for the most part. I'll try master and if that works could you make a new hackage release please?

**Comment by l-epple** [comment]
A new hackage release would be great indeed!

**Comment by yav** [comment]
I just put the current master (version 1.4.5.1) on hackage
